// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI agent that suggests traffic improvements based on traffic analysis and user inputs.
 *
 * - suggestTrafficImprovements - A function that suggests traffic improvements.
 * - SuggestTrafficImprovementsInput - The input type for the suggestTrafficImprovements function.
 * - SuggestTrafficImprovementsOutput - The return type for the suggestTrafficImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTrafficImprovementsInputSchema = z.object({
  trafficAnalysis: z
    .string()
    .describe('The analysis of the traffic flow at certain times.'),
  humanFlow: z.string().describe('Information about human flow in the area.'),
  jams: z.string().describe('Information about traffic jams experienced.'),
  delays: z.string().describe('Information about traffic delays experienced.'),
  signals: z.string().describe('Information about traffic signals in the area.'),
});
export type SuggestTrafficImprovementsInput = z.infer<
  typeof SuggestTrafficImprovementsInputSchema
>;

const SuggestTrafficImprovementsOutputSchema = z.object({
  suggestions: z
    .string()
    .describe('Suggestions for traffic improvements, such as lane and road adjustments.'),
});
export type SuggestTrafficImprovementsOutput = z.infer<
  typeof SuggestTrafficImprovementsOutputSchema
>;

export async function suggestTrafficImprovements(
  input: SuggestTrafficImprovementsInput
): Promise<SuggestTrafficImprovementsOutput> {
  return suggestTrafficImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTrafficImprovementsPrompt',
  input: {schema: SuggestTrafficImprovementsInputSchema},
  output: {schema: SuggestTrafficImprovementsOutputSchema},
  prompt: `You are an expert traffic planner.

  Based on the traffic analysis and user inputs, suggest ideas for traffic improvements, such as lane and road adjustments.

  Traffic Analysis: {{{trafficAnalysis}}}
  Human Flow: {{{humanFlow}}}
  Jams: {{{jams}}}
  Delays: {{{delays}}}
  Signals: {{{signals}}}`,
});

const suggestTrafficImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestTrafficImprovementsFlow',
    inputSchema: SuggestTrafficImprovementsInputSchema,
    outputSchema: SuggestTrafficImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
